#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Report Generator for Samsung CE Intelligence
Generates HTML and Markdown reports with deduplication statistics
"""

from datetime import datetime
from typing import List, Dict, Any
from collections import defaultdict

class ReportGenerator:
    """Generate formatted reports"""
    
    def __init__(self, config: Dict):
        self.config = config
        self.topic_names = {
            1: "Competitor Technology & Products",
            2: "New Technologies / Components / Materials",
            3: "Manufacturing Expansion (SEA / India)",
            4: "Exhibitions",
            5: "Supply Chain Risk"
        }
    
    def generate_markdown(self, articles: List[Dict], stats: Dict) -> str:
        """Generate Markdown report"""
        
        date_str = datetime.now().strftime('%B %d, %Y')
        
        # Group articles by topic
        articles_by_topic = defaultdict(list)
        for article in articles:
            for topic in article.get('topics', []):
                articles_by_topic[topic].append(article)
        
        # Build report
        report = []
        report.append(f"# Samsung CE Intelligence Brief")
        report.append(f"**Date:** {date_str}")
        report.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        report.append("")
        
        # Executive Summary
        report.append("## 📊 Executive Summary")
        report.append("")
        report.append(f"- **Total unique articles:** {len(articles)}")
        report.append(f"- **Duplicates removed:** {stats.get('duplicates_removed', 0)}")
        
        report.append("")
        report.append("| Topic | Count |")
        report.append("|-------|-------|")
        for topic_id in range(1, 6):
            count = len(articles_by_topic.get(topic_id, []))
            report.append(f"| {self.topic_names.get(topic_id, f'Topic {topic_id}')} | {count} |")
        
        # Deduplication Report
        report.append("")
        report.append("## 🔍 Deduplication Report")
        report.append("")
        report.append(f"- **Before dedup:** {stats.get('total_before', 0)} articles")
        report.append(f"- **After dedup:** {stats.get('total_after', 0)} articles")
        report.append(f"- **Removed:** {stats.get('duplicates_removed', 0)} duplicates")
        
        if stats.get('by_layer'):
            report.append("")
            report.append("**Detection by layer:**")
            for layer, count in stats['by_layer'].items():
                report.append(f"  - {layer}: {count}")
        
        # Topic Sections
        for topic_id in range(1, 6):
            topic_articles = articles_by_topic.get(topic_id, [])
            report.append("")
            report.append(f"## Topic {topic_id} — {self.topic_names.get(topic_id)}")
            report.append("")
            
            if not topic_articles:
                report.append("*No updates in this category*")
                continue
            
            # Generate appropriate table based on topic
            if topic_id == 1:
                report.append(self._generate_topic1_table(topic_articles))
            elif topic_id == 2:
                report.append(self._generate_topic2_table(topic_articles))
            elif topic_id == 3:
                report.append(self._generate_topic3_table(topic_articles))
            elif topic_id == 4:
                report.append(self._generate_topic4_table(topic_articles))
            elif topic_id == 5:
                report.append(self._generate_topic5_table(topic_articles))
        
        # Key Takeaways
        report.append("")
        report.append("## 💡 Key Takeaways for Samsung")
        report.append("")
        
        takeaways = []
        for topic_id, articles in articles_by_topic.items():
            if len(articles) > 0:
                takeaways.append(f"- **{self.topic_names.get(topic_id)}:** {len(articles)} relevant updates")
        
        if not takeaways:
            takeaways.append("- Continue monitoring market developments")
        
        report.extend(takeaways)
        
        # Footer
        report.append("")
        report.append("---")
        report.append(f"*Generated by Samsung CE Intelligence System v2.0*")
        
        return "\n".join(report)
    
    def _generate_topic1_table(self, articles: List[Dict]) -> str:
        """Generate table for Topic 1: Competitors"""
        if not articles:
            return "*No updates*"
        
        rows = ["| Company | Summary | Technology | Source | Confidence |"]
        rows.append("|---------|---------|------------|--------|------------|")
        
        for article in articles[:20]:
            company = self._extract_company(article)
            summary = article.get('summary', article.get('title', ''))[:100]
            tech = self._extract_technology(article)
            source = article.get('source', 'unknown')
            confidence = "🟢 High" if article.get('reliability_score', 0) > 0.85 else "🟡 Medium" if article.get('reliability_score', 0) > 0.7 else "🔴 Low"
            link = article.get('link', '#')
            
            rows.append(f"| **{company}** | {summary}... | {tech} | [{source}]({link}) | {confidence} |")
        
        return "\n".join(rows)
    
    def _generate_topic2_table(self, articles: List[Dict]) -> str:
        """Generate table for Topic 2: Technologies"""
        if not articles:
            return "*No updates*"
        
        rows = ["| Technology | Supplier | Summary | Source | Confidence |"]
        rows.append("|------------|----------|---------|--------|------------|")
        
        for article in articles[:20]:
            tech = self._extract_technology(article) or "New technology"
            supplier = self._extract_supplier(article) or "Various"
            summary = article.get('summary', article.get('title', ''))[:80]
            source = article.get('source', 'unknown')
            confidence = "🟢 High" if article.get('reliability_score', 0) > 0.85 else "🟡 Medium"
            link = article.get('link', '#')
            
            rows.append(f"| {tech} | {supplier} | {summary}... | [{source}]({link}) | {confidence} |")
        
        return "\n".join(rows)
    
    def _generate_topic3_table(self, articles: List[Dict]) -> str:
        """Generate table for Topic 3: Manufacturing Expansion"""
        if not articles:
            return "*No updates*"
        
        rows = ["| Company | Location | Investment | Status | Source | Confidence |"]
        rows.append("|---------|----------|------------|--------|--------|------------|")
        
        for article in articles[:15]:
            company = self._extract_company(article) or "Various"
            location = self._extract_location(article) or "SEA/India"
            summary = article.get('summary', article.get('title', ''))[:80]
            source = article.get('source', 'unknown')
            confidence = "🟢 High" if article.get('reliability_score', 0) > 0.85 else "🟡 Medium"
            link = article.get('link', '#')
            
            rows.append(f"| {company} | {location} | {summary}... | Expansion | [{source}]({link}) | {confidence} |")
        
        return "\n".join(rows)
    
    def _generate_topic4_table(self, articles: List[Dict]) -> str:
        """Generate table for Topic 4: Exhibitions"""
        if not articles:
            return "*No exhibitions today*"
        
        rows = ["| Exhibition | Location | Date | Source | Confidence |"]
        rows.append("|------------|----------|------|--------|------------|")
        
        for article in articles[:15]:
            title = article.get('title', 'Industry Exhibition')[:50]
            location = self._extract_location(article) or "TBD"
            date = ""
            if article.get('published_date'):
                date = article['published_date'].strftime('%Y-%m-%d')
            source = article.get('source', 'unknown')
            confidence = "🟢 High" if article.get('reliability_score', 0) > 0.85 else "🟡 Medium"
            link = article.get('link', '#')
            
            rows.append(f"| {title} | {location} | {date} | [{source}]({link}) | {confidence} |")
        
        return "\n".join(rows)
    
    def _generate_topic5_table(self, articles: List[Dict]) -> str:
        """Generate table for Topic 5: Supply Chain Risk"""
        if not articles:
            return "*No risk updates*"
        
        rows = ["| Risk Area | Summary | Impact | Source | Confidence |"]
        rows.append("|-----------|---------|--------|--------|------------|")
        
        for article in articles[:15]:
            risk = self._extract_risk(article) or "Supply Chain"
            summary = article.get('summary', article.get('title', ''))[:80]
            source = article.get('source', 'unknown')
            confidence = "🔴 High Risk" if article.get('reliability_score', 0) > 0.85 else "🟡 Medium Risk"
            link = article.get('link', '#')
            
            rows.append(f"| {risk} | {summary}... | Monitor | [{source}]({link}) | {confidence} |")
        
        return "\n".join(rows)
    
    def _extract_company(self, article: Dict) -> str:
        """Extract company name from article"""
        title = article.get('title', '').lower()
        companies = ['tcl', 'hisense', 'lg', 'sony', 'xiaomi', 'apple', 'huawei', 'samsung']
        for company in companies:
            if company in title:
                return company.upper()
        return "Various"
    
    def _extract_technology(self, article: Dict) -> str:
        """Extract technology name from article"""
        text = (article.get('title', '') + ' ' + article.get('summary', '')).lower()
        techs = ['oled', 'microled', 'miniled', 'qled', 'gan', 'sic', 'lidar', 'tof']
        for tech in techs:
            if tech in text:
                return tech.upper()
        return "New Technology"
    
    def _extract_supplier(self, article: Dict) -> str:
        """Extract supplier name from article"""
        text = (article.get('title', '') + ' ' + article.get('summary', '')).lower()
        suppliers = ['boe', 'csot', 'lg display', 'samsung display', 'qualcomm', 'mediatek', 'corning']
        for supplier in suppliers:
            if supplier in text:
                return supplier.title()
        return ""
    
    def _extract_location(self, article: Dict) -> str:
        """Extract location from article"""
        text = (article.get('title', '') + ' ' + article.get('summary', '')).lower()
        locations = ['vietnam', 'thailand', 'indonesia', 'india', 'malaysia', 'singapore']
        for loc in locations:
            if loc in text:
                return loc.title()
        return ""
    
    def _extract_risk(self, article: Dict) -> str:
        """Extract risk type from article"""
        text = (article.get('title', '') + ' ' + article.get('summary', '')).lower()
        if 'shortage' in text:
            return "Component Shortage"
        if 'tariff' in text or 'trade' in text:
            return "Trade Policy"
        if 'delay' in text:
            return "Delivery Delay"
        if 'quality' in text or 'recall' in text:
            return "Quality Issue"
        return "Supply Risk"
    
    def generate_html(self, markdown_content: str) -> str:
        """Convert Markdown to HTML"""
        import re
        
        date_str = datetime.now().strftime('%B %d, %Y')
        
        # Simple Markdown to HTML conversion
        html = markdown_content
        
        # Headers
        html = re.sub(r'^# (.*?)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.*?)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'^### (.*?)$', r'<h3>\1</h3>', html, flags=re.MULTILINE)
        
        # Bold
        html = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', html)
        
        # Links
        html = re.sub(r'\[(.*?)\]\((.*?)\)', r'<a href="\2">\1</a>', html)
        
        # Tables
        lines = html.split('\n')
        in_table = False
        table_html = []
        result = []
        
        for line in lines:
            if line.startswith('|') and not line.startswith('|---'):
                if not in_table:
                    in_table = True
                    table_html = ['<table>']
                cells = [c.strip() for c in line.split('|')[1:-1]]
                if '<th>' not in str(table_html):
                    table_html.append('<tr>' + ''.join(f'<th>{c}</th>' for c in cells) + '</tr>')
                else:
                    table_html.append('<tr>' + ''.join(f'<td>{c}</td>' for c in cells) + '</tr>')
            elif in_table and line.strip() == '':
                in_table = False
                table_html.append('</table>')
                result.append('\n'.join(table_html))
            else:
                if in_table:
                    in_table = False
                    table_html.append('</table>')
                    result.append('\n'.join(table_html))
                result.append(line)
        
        html = '\n'.join(result)
        
        # Wrap in full HTML template
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Samsung CE Intelligence - {date_str}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            line-height: 1.6;
        }}
        .container {{
            max-width: 1400px;
            margin: 0 auto;
            background: white;
            border-radius: 16px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }}
        .header {{
            background: linear-gradient(135deg, #1428a0 0%, #0f1a5e 100%);
            color: white;
            padding: 40px 50px;
        }}
        .header h1 {{
            font-size: 2.2em;
            margin-bottom: 10px;
            font-weight: 600;
        }}
        .header .date {{
            color: #ffd700;
            font-size: 1.1em;
            margin-top: 15px;
        }}
        .content {{
            padding: 40px 50px;
        }}
        h1 {{
            color: #1428a0;
            border-bottom: 3px solid #ffd700;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }}
        h2 {{
            color: #1428a0;
            margin: 30px 0 20px;
            padding-left: 15px;
            border-left: 5px solid #ffd700;
        }}
        h3 {{
            color: #333;
            margin: 20px 0 10px;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 0.85em;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }}
        th {{
            background: #f0f2f5;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            border-bottom: 2px solid #1428a0;
        }}
        td {{
            padding: 10px 12px;
            border-bottom: 1px solid #e2e8f0;
            vertical-align: top;
        }}
        tr:hover {{
            background: #f8fafc;
        }}
        a {{
            color: #1428a0;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        .footer {{
            background: #f0f2f5;
            padding: 20px 50px;
            text-align: center;
            color: #64748b;
            font-size: 0.85em;
            border-top: 1px solid #e2e8f0;
        }}
        @media (max-width: 768px) {{
            .header, .content {{
                padding: 20px;
            }}
            table {{
                font-size: 0.75em;
            }}
            th, td {{
                padding: 6px;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔵 Samsung Consumer Electronics</h1>
            <p>Strategic Technology & Sourcing Intelligence</p>
            <div class="date">📅 {date_str} · Daily Briefing</div>
        </div>
        <div class="content">
            {self._markdown_to_html(html)}
        </div>
        <div class="footer">
            <p>🔵 Generated by Samsung CE Intelligence System v2.0</p>
            <p>📡 Multi-source aggregation with 3-layer deduplication</p>
        </div>
    </div>
</body>
</html>"""
    
    def _markdown_to_html(self, md: str) -> str:
        """Convert markdown to HTML (basic)"""
        import re
        
        # Convert paragraphs
        paragraphs = re.split(r'\n\s*\n', md)
        html_parts = []
        
        for para in paragraphs:
            if para.strip():
                if para.startswith('<h') or para.startswith('<td>') or para.startswith('<ul'):
                    html_parts.append(para)
                else:
                    html_parts.append(f'<p>{para}</p>')
        
        return '\n'.join(html_parts)
